export const replaceTable = {

    'project_name': '项目名称',
    'project_creator_name': '项目创建人',
    'project_creator_id': '项目创建人id',
    'project_creator_email': '创建人邮箱',
    'project_manager_id': '项目经理id',
    'project_manager_name': '项目经理',
    'project_manager_email': '项目经理邮箱',
    'organization_name': '组织名称',
    'organization_id': '组织id',
    'customer_contact': '用户联系',
    'contact_email': '组织邮箱',
    'liaison_name': '联系人',
    'liaison_email': '联系人邮箱',
    'liaison_id': '联系人id',
    'test_number': '电话号码',
    'is_frozen': '是否冻结',
    'frozen_by': '被谁冻结',
    'is_locked': '是否锁定',
    'locked_by': '被谁锁定',
    'comment': '意见',
    'status': '状态',
    'create_time': '创建时间',
    'orgid': '组织id',
    'modified_time': '更改时间',

    'name': '名称',
    'logopath': 'LOGO',
    'istoporg': '顶级组织',
    'higherorgid': '上级组织id',
    'islocked': '是否暂停',
    'isfrozen': '是否冻结',
    'createtime': '创建时间',
    'modifytime': '修改时间',
    'freezetime': '冻结时间',
    'clientcontact': '客户联系',
    'comments': '意见',
    'id': '编号',

    'type': '类型',
    'operator_id': '执行人id',
    'role': '角色',
    'operator': '执行人',
    'details': '详情',
    'time': '时间',

    'projectname': '项目名称',
    'project_manager': '项目执行人',
    'organization_name': '组织名称',
    'customer_contact': '用户联系',
    'contact_email': '组织邮箱',
    'liaison_name': '联系人',
    'liaison_email': '联系人邮箱',
    'liaison_id': '联系人id',
    'test_number': '电话号码',
    'is_frozen': '是否冻结',
    'frozen_by': '被谁冻结',
    'is_locked': '是否锁定',
    'locked_by': '被谁锁定',
    'comment': '意见',
    'status': '状态',
    'create_time': '创建时间',
    'orgid': '组织id',
    'modified_time': '更改时间',
    'name': '名称',
    'logopath': 'LOGO',
    'istoporg': '顶级组织',
    'higherorgid': '上级组织id',
    'islocked': '是否锁定',
    'isfrozen': '是否冻结',
    'createtime': '创建时间',
    'modifytime': '修改时间',
    'freezetime': '冻结时间',
    'clientcontact': '客户联系',
    'comments': '意见',
    'puasetime': '暂停时间',

    'project_id': '所属项目编号',
    'type': '类型',
    'report_status': '报告状态',
    'delivery_freq': '发件频率',
    'delivery_address': '发件地址',
    'pause_time': '暂停时间',
    'subject': '主题',

    'username': '用户名',
    'sysrole': '角色',
    
    'delivery_time': '发件时间',
    'server': '服务器',
    'port': '端口',
    'encryptalg': '编码方式',
    'locktime': '锁定时间',
    'createdbyuid': '创建人id',
    'modifiedbyuid': '修改人id',
    'content': '内容',
    'attachid': '附件',
    'modifybyuid': '修改人id',
    'frozenbyuid': '冻结人id'

}
